# Generated by Django 5.0.6 on 2024-07-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0014_feedback_to_comparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
